-- 1 : CANTIDAD DE EMPLEADOS CON
-- A : SALARIO MENOR A 3.500 USD
select count(0) EMPLOYEES_COUNT from employees e where SALARY < 3500

-- B : SALARIO MAYOR O IGUAL A 3.500 Y MENOR QUE 8.000
select count(0) EMPLOYEES_COUNT from employees e where SALARY >= 3500 and SALARY < 8000

-- C : SALARIO MAYOR O IGUAL A 8.000
select count(0) EMPLOYEES_COUNT from employees e where SALARY >= 8000

-- 2 : CANTIDAD DE EMPLEADOS POR DEPARTAMENTO CON
-- A : SALARIO MENOR A 3.500 USD
select DEPARTMENT_NAME, count(0) EMPLOYEES_COUNT from departments d inner join employees e on d.DEPARTMENT_ID = e.DEPARTMENT_ID 
where SALARY < 3500 group by DEPARTMENT_NAME order by EMPLOYEES_COUNT

-- B : SALARIO MAYOR O IGUAL A 3.500 Y MENOR QUE 8.000
select DEPARTMENT_NAME, count(0) EMPLOYEES_COUNT from departments d inner join employees e on d.DEPARTMENT_ID = e.DEPARTMENT_ID 
where SALARY >= 3500 and SALARY < 8000 group by DEPARTMENT_NAME order by EMPLOYEES_COUNT

-- C : SALARIO MAYOR O IGUAL A 8.000
select DEPARTMENT_NAME, count(0) EMPLOYEES_COUNT from departments d inner join employees e on d.DEPARTMENT_ID = e.DEPARTMENT_ID 
where SALARY >= 8000 group by DEPARTMENT_NAME order by EMPLOYEES_COUNT

-- 3 : INFORMACION DEL EMPLEADO CON MAYOR SUELDO POR DEPARTAMENTO
select FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, DEPARTMENT_NAME, MAX(SALARY) SALARY  from departments d 
inner join employees e on d.DEPARTMENT_ID = e.DEPARTMENT_ID  group by DEPARTMENT_NAME order by SALARY

-- 4 : INFORMACION DE LOS GERENTES QUE HAYAN SIDO CONTRATADOS HACE MAS DE 15 AÑOS
select FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, JOB_TITLE ,HIRE_DATE, SALARY, (year(now()) - year(HIRE_DATE)) YEARS from employees e2 
inner join jobs j2 on e2.JOB_ID = j2.JOB_ID where j2.JOB_TITLE like '%MANAGER%' and (year(now()) - year(HIRE_DATE)) > 15

-- 5 : SALARIO PROMEDIO DE TODOS LOS DEPARTAMENTOS CON MAS DE 10 EMPLEADOS
select DEPARTMENT_NAME, count(0) EMPLOYEES_COUNT, TRUNCATE(AVG(SALARY),0) AVG_SALARY from departments d 
inner join employees e on d.DEPARTMENT_ID = e.DEPARTMENT_ID  
group by DEPARTMENT_NAME having count(0) > 10 

-- 6 : CANTIDAD DE EMPLEADOS, SALARIO PROMEDIO, MAXIMO Y MINIMO, PROMEDIO DE AÑOS DE ANTIGUEDAD POR PAIS